name: A workflow for GROUP 2
on: push

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: temurin
      - name: Unit Tests
        run: mvn -Dtest=com.napier.proj.report.AppUnitTest test
      - name: CodeCov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # now required for public repos too
          directory: ./target/site/jacoco
          flags: unittests # optional
          verbose: true # optional (default = false)
          slug: ph0neMyatThu4079/group-2-project

  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: temurin
      - name: Integration Tests
        run: |
          docker build -t database ./db 
          docker run --name world -dp 33060:3306 database
          mvn -Dtest=com.napier.proj.dao.AppIntegrationTest test
          docker stop world
          docker rm world
          docker image rm database
      - name: CodeCov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # now required for public repos too
          directory: ./target/site/jacoco
          flags: integration # optional
          verbose: true # optional (default = false)
          slug: ph0neMyatThu4079/group-2-project

  # New job to merge coverage reports
  MergeCoverage:
    needs: [UnitTests, IntegrationTests]
    runs-on: ubuntu-latest
    steps:
      - name: Merge Codecov reports
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests,integration
          slug: ph0neMyatThu4079/group-2-project

  build:
    name: Group 2 Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests

          sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

          docker-compose up --abort-on-container-exit --exit-code-from app

#      - name: Build with Maven
#        run: mvn package
#
#      - name: Install Docker Compose
#        run: |
#          sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#          sudo chmod +x /usr/local/bin/docker-compose
#          docker-compose --version
#
#      - name: Run docker compose
#        run: docker-compose up --abort-on-container-exit --exit-code-from app
